### ISSUE TITLE
pymoogi abfind_example.par  (Error)

### ISSUE THREAD

**Issue by denizcdursun** [madamow/pymoogi#22]
Hello,

I'm a macOS user. I am having trouble running the program. 
"pymoogi synth_example.par" works fine. 
But when I run the "abfind" file, it gives an error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pymoogi", line 33, in <module>
    sys.exit(load_entry_point('pyMOOGi==1.0.0', 'console_scripts', 'pymoogi')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymoogi/__main__.py", line 31, in main
    driver, params = list_to_dict(open(syn_file).read())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymoogi/lib/Common_functions.py", line 74, in list_to_dict
    dict_par[line[0]].append(line[1])
IndexError: list index out of range
```

**Comment by madamow** [comment]
How do you run abfind? The error you posted refers to code specific for synth driver. It is not in abfind at all.

**Comment by denizcdursun** [comment]
Hello again, I missed the " character at the end of the line_list path. That's why it gives an error. Thank you.
